version: "3.8"

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "2747"]
    ports:
      - 2747:2747
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:2747'}]}) }" | mongosh --port 2747 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - asgn

  backend:
    build: ./server
    container_name: backend
    ports:
      - 3001:3001
    depends_on:
      - mongo1
    volumes:
      - ./server:/app
    networks:
      - asgn

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - 8001:5173
    networks:
      - asgn

networks:
  asgn:
    driver: bridge

volumes:
  mongo1_data:
  mongo1_config: